name: Sync repositories

on:
  # Manual trigger
  workflow_dispatch:
  
  # Run every 6 hours
  schedule:
    - cron: '0 */6 * * *'

jobs:
  sync-repositories:
    runs-on: ubuntu-latest
    # Add permissions for the GITHUB_TOKEN
    permissions:
      contents: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      # Use pre-installed GitHub CLI instead of setup action
      - name: Configure GitHub CLI authentication
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
      
      - name: Sync ot-setup repository
        run: |
          # Create temporary directory
          mkdir -p ./tmp/ot-setup
          cd ./tmp/ot-setup
          
          # Clone source repository from GitLab
          git clone --mirror https://gitlab.opencode.de/opentalk/ot-setup.git .
          
          # Configure Git
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          
          # Use git push instead of gh repo sync
          # Configure GitHub remote with token
          git remote add github https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/opencloud-community/ot-setup.git
          
          # Push to GitHub target repository
          git push --mirror github
          
          # Cleanup
          cd ../..
          rm -rf ./tmp/ot-setup
      
      - name: Sync ot-docs repository
        run: |
          # Create temporary directory
          mkdir -p ./tmp/ot-docs
          cd ./tmp/ot-docs
          
          # Clone source repository from GitLab
          git clone --mirror https://gitlab.opencode.de/opentalk/docs.git .
          
          # Configure Git
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          
          # Use git push instead of gh repo sync
          # Configure GitHub remote with token
          git remote add github https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/opencloud-community/ot-docs.git
          
          # Push to GitHub target repository
          git push --mirror github
          
          # Cleanup
          cd ../..
          rm -rf ./tmp/ot-docs